### ISSUE TITLE
runnable jar creation should be easier

### ISSUE THREAD

**Issue by biotomas** [domschrei/aquaplanning#1]
Update pom.xml such that maven would build the project and create a runnable aquaplanning.jar file. All this should work without eclipse.

**Comment by biotomas** [comment]
Did Patrick already implement this in his fork? https://github.com/patrickhegemann/aquaplanning/commit/4f24ed7186708667c862ed76e945812df5e69574

**Comment by patrickhegemann** [comment]
Yes :-) See #2

**Comment by domschrei** [comment]
Thanks Patrick! I can update the Readme with according instructions.
