### ISSUE TITLE
Error while parsing domain with action costs

### ISSUE THREAD

**Issue by patrickhegemann** [domschrei/aquaplanning#10]
I have this code in my domain file:
```
    (:functions (total-cost) - number)

    (:predicates
        ;...
```

When trying to solve problems with Aquaplanning I get this error:
```
Parsing...
line 28:5 no viable alternative at input '(:predicates'
Parsing error in domain.pddl at (line 26, col. 31) until (line 26, col. 31):
Unrecognized or illegal token "(".
```

**Comment by domschrei** [comment]
Can you test if it works when putting the `(:functions ...)` definition _below_ the `(:predicates ...)` definition?

**Comment by patrickhegemann** [comment]
Yes, that works indeed. Shouldn't we update the grammar then?

**Comment by domschrei** [comment]
Well, actually the official EBNF of PDDL3.1 says so, too. 

So I would probably just leave it as it is ¯\\\_(ツ)\_/¯
