### ISSUE TITLE
Converting a state into a goal

### ISSUE THREAD

**Issue by jtrautmann** [domschrei/aquaplanning#21]
I have a problem maybe somebody can help me with:
Given a `GroundPlanningProblem` and a `State` instance, I want to convert the `State` into a new `Goal` instance, using all atoms. My approach was getting the atom values by using the `State.getAtoms()` method. For each of the values, I need to build an `Atom` instance, so I just used the index in the atoms list as the ID because that seemed to be right. For the name, I first used just an empty string, but this didn't work in all cases. So I wanted to use the `GroundPlanningProblem.getAtomNames()` method, but it turned out that this list is smaller than the one returned by `State.getAtoms()`. I don't really understand how this can be. Maybe you could explain it?
But most importantly: Could you maybe explain how one can convert a `State` into a `Goal` instance?

**Comment by domschrei** [comment]
It's weird that `getAtomNames()` returns a list shorter than the maximum set index in `State.getAtoms()`. Could you maybe provide an example where this is the case? If it's a bug, I can try and find it.

I guess it would make sense to add a constructor `Goal(State state)`. Maybe, to provide the actual correct atom names, even something like `Goal(State state, Function<Integer, String> atomNames)`.

**Comment by jtrautmann** [comment]
> It's weird that `getAtomNames()` returns a list shorter than the maximum set index in `State.getAtoms()`. Could you maybe provide an example where this is the case? If it's a bug, I can try and find it.

[ExamplePlanOptimizer.zip](https://github.com/domschrei/aquaplanning/files/2827469/ExamplePlanOptimizer.zip)

Here you have a minimal example to show the described problem. Just use it through the TestPlanOptimizer. I get the following output:

> Testing plan improver on /home/jeremias/Programmieren/KIT/APS/aquaplanning/benchmarks/Rover/p07.pddl.sas.plan.zip
> initial plan valid: true
> atomsBool 320
> atomNames 257

If I didn't get it wrong, these to numbers should be equal.

**Comment by jtrautmann** [comment]
I can confirm this is working now. Thank you!
