### ISSUE TITLE
Maven Build Failure

### ISSUE THREAD

**Issue by biotomas** [domschrei/aquaplanning#3]
[error.log](https://github.com/domschrei/aquaplanning/files/2545975/error.log)

**Comment by domschrei** [comment]
This seems to be a very recent bug in openjdk8 and in Surefire, see [this SO post](https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class). We can try one of the following potential fixes:

* Try adding these lines to the `<plugins>` in our `pom.xml`:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.1</version>
    <configuration>
        <useSystemClassLoader>false</useSystemClassLoader>
    </configuration>
</plugin>
```
* If this does not work, another proposed fix is to add the option `-Djdk.net.URLClassPath.disableClassPathURLCheck=true`, e.g. by creating and/or modifying `~/.m2/settings.xml` with the following profile definition:
```
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <pluginGroups></pluginGroups>
  <proxies></proxies>
  <servers></servers>
  <mirrors></mirrors>
  <profiles>
    <profile>
        <id>SUREFIRE-1588</id>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
        <properties>
            <argLine>-Djdk.net.URLClassPath.disableClassPathURLCheck=true</argLine>
        </properties>
    </profile>
  </profiles>
</settings>
```

**Comment by biotomas** [comment]
Adding the plugin fixed the issue, thanks Dominik :+1:
