### ISSUE TITLE
Build Errors, a lot of them

### ISSUE THREAD

**Issue by femigr** [domschrei/aquaplanning#7]
[debug-log.txt](https://github.com/domschrei/aquaplanning/files/2672068/debug-log.txt)

**Comment by biotomas** [comment]
there is no error on my computer, what OS do you use?

**Comment by femigr** [comment]
Ubuntu Linux 18.04.1 LTS

**Comment by domschrei** [comment]
Hi, the file `FullEnumerationGrounder.java` should not exist in the current state of the framework (it was removed). If you pull a fresh state of the repository, everything should build fine. You can also `git status` in your current aquaplanning directory to see which changes your current workplace has compared to the master branch.
